name: Generate XML Feed
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/xml-feed/**'
      - '.github/workflows/generate-xml-feeds.yaml'
jobs:
  update_zillow_feed:
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      pull-requests: read
      contents: write
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Configure git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        working-directory: ./.github/xml-feed
        run: npm install
      - name: Run script
        working-directory: ./.github/xml-feed
        run: |
          node generate-xml-feed.js
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'admin/aIncludeInZillow/*.xml'
          commit_message: "Update XML Feed"